service:
  name: serverless-images

plugins:
  - serverless-webpack

provider:
  name: aws
  runtime: nodejs8.10
  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:PutObject
      Resource: "arn:aws:s3:::serverless-images-bucket/*"

resources:
  Resources:
    imagesBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: serverless-images-bucket

functions:
  resize:
    handler: handler.resize
    events:
      - http:
          method: post
          path: resize
